# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('happenings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_event_id', models.IntegerField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='happenings.Event')),
            ],
        ),
    ]
