# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 15:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookevent',
            name='facebook_cover_image_url',
            field=models.TextField(default='http://image.png', validators=[django.core.validators.URLValidator()]),
        ),
    ]
